services:
  day20-db:
    restart: unless-stopped
    image: mongo:latest
    container_name: day20-mongo
    ports:
      - "${MONGO_PORT:-}:27017"
    volumes:
      - day20_data:/data/db
    networks:
      - day20-network

  day20-api:
    restart: unless-stopped
    build: ./backend
    container_name: day20-elysia
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    environment:
      - MONGO_URI=mongodb://day20-db:27017/day20
      - BUN_ENV=production
    depends_on:
      - day20-db
    networks:
      - day20-network

  day20-ui:
    restart: unless-stopped
    build: ./frontend
    container_name: day20-vue
    ports:
      - "3500:3500"
    networks:
      - day20-network

networks:
  day20-network:
    driver: bridge

volumes:
  day20_data:
